import re

# List of common prompt injection keywords / phrases
PROMPT_INJECTION_KEYWORDS = [
    "ignore previous instructions",
    "ignore the instructions above",
    "bypass restrictions",
    "system prompt",
    "override",
    "you are now a",
    "you must now act as",
    "forget everything",
    "dan mode",
    "jailbreak",
    "do not follow the guidelines"
]

def check_input_guardrail(query: str) -> tuple[bool, str]:
    """
    Checks the user query for prompt injections or out-of-scope topics.
    Returns (is_safe, failure_reason).
    """
    if not query or not query.strip():
        return False, "Query cannot be empty."

    query_lower = query.lower()

    # 1. Prompt Injection Check
    for keyword in PROMPT_INJECTION_KEYWORDS:
        if keyword in query_lower:
            return False, f"Potential prompt injection detected (keyword: '{keyword}')."
            
    # 2. Heuristic check to prevent malicious scripts/code injections
    if re.search(r"<script>|javascript:|onerror=|onload=", query_lower):
        return False, "Potential script injection detected."

    # 3. Simple Scope Check
    # The application is an AI Research Paper Summarizer & Report Generator.
    # We want to encourage academic, scientific, or research-oriented questions.
    # While we don't want to block basic inquiries, we should block highly out-of-scope items
    # like casual chatting, offensive terms, or system hacking attempts.
    out_of_scope_indicators = [
        "hack into", "crack password", "steal data", "ddos", "pirate software"
    ]
    for indicator in out_of_scope_indicators:
        if indicator in query_lower:
            return False, f"Out-of-scope request regarding cybersecurity attack/theft detected."

    return True, "Query passed all input guardrails."

def check_output_guardrail(generated_output: str, retrieved_contexts: list[str]) -> tuple[bool, str, float]:
    """
    Verifies that the generated summary/report is grounded in the retrieved context.
    Uses keyword/entity overlap to estimate hallucination risk.
    Returns (is_grounded, details_message, overlap_score).
    """
    if not generated_output or not generated_output.strip():
        return True, "Output is empty.", 1.0
        
    if not retrieved_contexts:
        return False, "No retrieved context available to verify against.", 0.0

    # Combine all contexts
    full_context = " ".join(retrieved_contexts).lower()
    
    # Extract candidate entities/terms from generated output:
    # 1. Words starting with a capital letter (proper nouns, names, formulas) - exclude start of sentences
    # 2. Numbers (integers, decimals, percentages, e.g., "98%", "2024")
    # 3. Long scientific/technical words (length > 6)
    
    # A simple way: find all words with length > 5 or containing digits
    words = re.findall(r'\b[a-zA-Z0-9-]{6,}\b', generated_output)
    
    # Also find all numbers
    numbers = re.findall(r'\b\d+(?:\.\d+)?%?\b', generated_output)
    
    candidates = list(set(words + numbers))
    
    # Filter candidates: remove common words to avoid noise
    common_stop_words = {
        "summary", "report", "research", "paper", "author", "authors", "system",
        "method", "result", "results", "analysis", "section", "figure", "table",
        "introduction", "conclusion", "discussion", "abstract", "proposed", "presents",
        "information", "generation", "summarizer"
    }
    candidates = [c for c in candidates if c.lower() not in common_stop_words]
    
    if not candidates:
        # If there are no complex terms or numbers, check basic word overlap
        candidates = list(set(re.findall(r'\b\w{4,}\b', generated_output.lower())))
        candidates = [c for c in candidates if c not in common_stop_words][:20]
        
    if not candidates:
        return True, "Simple output with insufficient technical terms to verify hallucination. Passed.", 1.0

    # Check how many candidates appear in the retrieved context
    matched_candidates = []
    unmatched_candidates = []
    
    for candidate in candidates:
        # Check matching (case-insensitive)
        pattern = re.escape(candidate.lower())
        if re.search(pattern, full_context):
            matched_candidates.append(candidate)
        else:
            unmatched_candidates.append(candidate)
            
    overlap_ratio = len(matched_candidates) / len(candidates)
    
    # We establish a threshold of 60% overlap for groundedness.
    # Scientific papers use specific technical terms, so if they are generated by the LLM,
    # they should almost certainly be in the retrieved text.
    threshold = 0.60
    
    if overlap_ratio >= threshold:
        return (
            True, 
            f"Output is grounded in retrieved context (Overlap: {overlap_ratio:.1%}). "
            f"Verified terms: {', '.join(matched_candidates[:5])}...",
            overlap_ratio
        )
    else:
        return (
            False,
            f"Potential hallucination detected (Overlap: {overlap_ratio:.1%}). "
            f"Terms not found in source text: {', '.join(unmatched_candidates[:5])}",
            overlap_ratio
        )
