import os
from rag_pipeline import run_rag_query
from guardrails import check_output_guardrail

# Queries to validate
queries = [
    "Compare cardiovascular risk prediction and sepsis detection using AI",
    "How is AI transforming drug discovery and target identification?",
    "How are transformer models used in healthcare and biomedical research?"
]

def run_validation():
    print("==================================================")
    print("          NovaRAG Retrieval Validation            ")
    print("==================================================")
    
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("[WARNING] GEMINI_API_KEY environment variable is not set. The RAG pipeline will run in fallback (offline raw retrieval) mode unless API key is defined in .env.")
    
    for idx, query in enumerate(queries):
        print(f"\nQUERY {idx+1}: '{query}'")
        print("-" * 50)
        
        result = run_rag_query(query, api_key=api_key)
        
        print(f"Status: {result['status']}")
        print(f"Retrieved & Reranked Chunks: {len(result['raw_chunks'])}")
        print("Top Retrieved Chunks:")
        for chunk in result['raw_chunks'][:3]:
            print(f"  - Rank {chunk['rank']}: {chunk['title']} (Page {chunk['page']})")
            
        print("\nSummary generated by RAG:")
        print(result['summary'])
        
        # Groundedness Check
        contexts = [c["text"] for c in result["raw_chunks"]]
        if result['status'] == "success":
            is_grounded, msg, score = check_output_guardrail(result['summary'], contexts)
            print(f"\nGroundedness Check:")
            print(f"  Is Grounded: {is_grounded}")
            print(f"  Score: {score:.1%}")
            print(f"  Message: {msg}")
        else:
            print("\nGroundedness Check: N/A (API Fallback active)")
        print("=" * 60)

if __name__ == "__main__":
    run_validation()
